FROM golang:latest as build

ENV GO11MODULE=on

WORKDIR /go/app

COPY . .

RUN go build -o app \
    && go get github.com/markbates/refresh

FROM alpine

WORKDIR /app

COPY --from=build /go/app/app .

RUN addgroup go \
  && adduser -D -G go go \
  && chown -R go:go /app/app

CMD ["./app"]
